# Generated by Django 6.0.2 on 2026-02-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image_alter_blog_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_date',
        ),
    ]
